sonar.projectName=Baseline App
sonar.sources=.
sonar.python.coverage.reportPaths=coverage.xml
sonar.projectKey=baseline-app
sonar.host.url=http://localhost:9000
sonar.login=sqp_15946d8ea2e855b821bb7f839b9cdb0a7efeeb1d
sonar.exclusions=tests/**,docs/**, .vscode/**, .git/**, coverage/**, .venv/**, .idea/**, .pytest_cache/**, .pytype/**, __pycache__/**, *.pyc